### ISSUE TITLE
Content assist stuck showing "Loading..." on Windows

### ISSUE THREAD

**Issue by willsmythe** [Microsoft/vscode-azurecli#13]
Intelli-sense/content assist does not present valid values; only "Loading...".

1. Installed the Azure CLI extension
2. Created a new .azcli file and opened it
3. Typed `az ` and CTRL+SPACE
4. "Loading..." appeared, but never presented anby options. No visible errors. "Loading..." just continues to show.

![image](https://user-images.githubusercontent.com/2503052/29046208-6b00a4c4-7b94-11e7-887f-3bbaf3603ad9.png)

From the VS Code Integrated Terminal, running "az --version" works as expected.

### VS Code
1.14.2
### AZ CLI (installed silently via MSI)
azure-cli (2.0.7)
Python (Windows) 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 17:54:52) [MSC v.1900 32 bit (Intel)]
Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
### Azure CLI Tools
0.1.0

**Comment by willsmythe** [comment]
Open the developer tools in Code shows the following error when its attempting to load content assist:

```
[Extension Host] Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\core\commands\__init__.py", line 461, in get_op_handler
    op = import_module(mod_to_import)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\command_modules\network\custom.py", line 149, in <module>
    sku=ApplicationGatewaySkuName.standard_medium.value,
AttributeError: 'NoneType' object has no attribute 'standard_medium'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\wismythe\.vscode\extensions\ms-vscode.azurecli-0.1.0\service\azservice\__main__.py", line 335, in <module>
    main()
  File "C:\Users\wismythe\.vscode\extensions\ms-vscode.azurecli-0.1.0\service\azservice\__main__.py", line 304, in main
    command_table = load_command_table()
  File "C:\Users\wismythe\.vscode\extensions\ms-vscode.azurecli-0.1.0\service\azservice\tooling.py", line 63, in load_command_table
    _install_modules(command_table)
  File "C:\Users\wismythe\.vscode\extensions\ms-vscode.azurecli-0.1.0\service\azservice\tooling.py", line 68, in _install_modules
    command_table[cmd].load_arguments()
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\core\commands\__init__.py", line 312, in load_arguments
    self.arguments.update(self.arguments_loader())
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\core\commands\__init__.py", line 577, in arguments_loader
    return extract_args_from_signature(get_op_handler(operation), no_wait_param=no_wait_param)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\core\commands\__init__.py", line 468, in get_op_handler
    raise ValueError("The operation '{}' is invalid.".format(operation))
ValueError: The operation 'azure.cli.command_modules.network.custom#create_application_gateway' is invalid.

h.logExtensionHostMessage @ extensionHost.ts:320
(anonymous) @ extensionHost.ts:176
emitTwo @ events.js:106
emit @ events.js:191
process.nextTick @ internal/child_process.js:752
_combinedTickCallback @ internal/process/next_tick.js:67
_tickCallback @ internal/process/next_tick.js:98
```

**Comment by chrmarti** [comment]
@willsmythe Could you upgrade your `az` installation? I remember there was an issue sometime around 2.0.7 (not sure about the exact version).

**Comment by chrmarti** [comment]
Closing with no additional feedback being provided.
