### ISSUE TITLE
completions not found, then extension host crash

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode-azurecli#14]
VS Code running overnight on closed laptop, logged in this morning and see this:

![image](https://user-images.githubusercontent.com/1487073/29470101-ebe7b280-83ff-11e7-9173-f26167036f20.png)

Open developer tools, see this in console:

``` console
[Extension Host] Completions not found (group create --name)

t.logExtensionHostMessage @ extensionHost.ts:337
extensionHost.ts:337 [Extension Host] Completions not found (appservice plan create --name)

t.logExtensionHostMessage @ extensionHost.ts:337
extensionHost.ts:337 [Extension Host] Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main

t.logExtensionHostMessage @ extensionHost.ts:337
extensionHost.ts:337 [Extension Host]     "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code

t.logExtensionHostMessage @ extensionHost.ts:337
extensionHost.ts:337 [Extension Host]     exec code in run_globals
  File "/Users/chris/.vscode-insiders/extensions/ms-vscode.azurecli-0.1.0/service/azservice/__main__.py", line 335, in <module>
    main()
  File "/Users/chris/.vscode-insiders/extensions/ms-vscode.azurecli-0.1.0/service/azservice/__main__.py", line 326, in main

t.logExtensionHostMessage @ extensionHost.ts:337
extensionHost.ts:337 [Extension Host]     response_data = get_completions(group_index, command_table, snippets, request['data'], True)
  File "/Users/chris/.vscode-insiders/extensions/ms-vscode.azurecli-0.1.0/service/azservice/__main__.py", line 114, in get_completions
    return get_argument_value_completions(command_table, query, verbose)
  File "/Users/chris/.vscode-insiders/extensions/ms-vscode.azurecli-0.1.0/service/azservice/__main__.py", line 182, in get_argument_value_completions
    list = get_argument_value_list(command_table, query, verbose) + \
  File "/Users/chris/.vscode-insiders/extensions/ms-vscode.azurecli-0.1.0/service/azservice/__main__.py", line 200, in get_argument_value_list

t.logExtensionHostMessage @ extensionHost.ts:337
extensionHost.ts:337 [Extension Host]     values = run_argument_value_completer(command, argument, query['arguments'])
  File "/Users/chris/.vscode-insiders/extensions/ms-vscode.azurecli-0.1.0/service/azservice/tooling.py", line 130, in run_argument_value_completer

t.logExtensionHostMessage @ extensionHost.ts:337
extensionHost.ts:337 [Extension Host]     return argument.completer('', '', args)
  File "/Users/chris/lib/azure-cli/lib/python2.7/site-packages/azure/cli/core/commands/parameters.py", line 83, in completer

t.logExtensionHostMessage @ extensionHost.ts:337
extensionHost.ts:337 [Extension Host]     return [r.name for r in get_resources_in_resource_group(rg, resource_type=resource_type)]
  File "/Users/chris/lib/azure-cli/lib/python2.7/site-packages/azure/cli/core/commands/parameters.py", line 69, in get_resources_in_resource_group

t.logExtensionHostMessage @ extensionHost.ts:337
extensionHost.ts:337 [Extension Host]     return list(rcf.resource_groups.list_resources(resource_group_name, filter=filter_str))
AttributeError: 'ResourceGroupsOperations' object has no attribute 'list_resources'

t.logExtensionHostMessage @ extensionHost.ts:337
extensionHost.ts:337 [Extension Host] Exit code 1, signal null
t.logExtensionHostMessage @ extensionHost.ts:337
extensionHost.ts:337 [Extension Host] Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main

t.logExtensionHostMessage @ extensionHost.ts:337
extensionHost.ts:337 [Extension Host]     "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/chris/.vscode-insiders/extensions/ms-vscode.azurecli-0.1.0/service/azservice/__main__.py", line 335, in <module>
    main()
  File "/Users/chris/.vscode-insiders/extensions/ms-vscode.azurecli-0.1.0/service/azservice/__main__.py", line 326, in main
    response_data = get_completions(group_index, command_table, snippets, request['data'], True)
  File "/Users/chris/.vscode-insiders/extensions/ms-vscode.azurecli-0.1.0/service/azservice/__main__.py", line 114, in get_completions
    return get_argument_value_completions(command_table, query, verbose)
  File "/Users/chris/.vscode-insiders/extensions/ms-vscode.azurecli-0.1.0/service/azservice/__main__.py", line 182, in get_argument_value_completions
    list = get_argument_value_list(command_table, query, verbose) + \
  File "/Users/chris/.vscode-insiders/extensions/ms-vscode.azurecli-0.1.0/service/azservice/__main__.py", line 200, in get_argument_value_list
    values = run_argument_value_completer(command, argument, query['arguments'])
  File "/Users/chris/.vscode-insiders/extensions/ms-vscode.azurecli-0.1.0/service/azservice/tooling.py", line 130, in run_argument_value_completer

t.logExtensionHostMessage @ extensionHost.ts:337
extensionHost.ts:337 [Extension Host]     return argument.completer('', '', args)
  File "/Users/chris/lib/azure-cli/lib/python2.7/site-packages/azure/cli/core/commands/parameters.py", line 83, in completer
    return [r.name for r in get_resources_in_resource_group(rg, resource_type=resource_type)]
  File "/Users/chris/lib/azure-cli/lib/python2.7/site-packages/azure/cli/core/commands/parameters.py", line 69, in get_resources_in_resource_group
    return list(rcf.resource_groups.list_resources(resource_group_name, filter=filter_str))
AttributeError: 'ResourceGroupsOperations' object has no attribute 'list_resources'

t.logExtensionHostMessage @ extensionHost.ts:337
extensionHost.ts:337 [Extension Host] Exit code 1, signal null
t.logExtensionHostMessage @ extensionHost.ts:337
extensionHost.ts:337 [Extension Host] Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main

t.logExtensionHostMessage @ extensionHost.ts:337
extensionHost.ts:337 [Extension Host]     "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/chris/.vscode-insiders/extensions/ms-vscode.azurecli-0.1.0/service/azservice/__main__.py", line 335, in <module>
    main()
  File "/Users/chris/.vscode-insiders/extensions/ms-vscode.azurecli-0.1.0/service/azservice/__main__.py", line 326, in main
    response_data = get_completions(group_index, command_table, snippets, request['data'], True)
  File "/Users/chris/.vscode-insiders/extensions/ms-vscode.azurecli-0.1.0/service/azservice/__main__.py", line 114, in get_completions
    return get_argument_value_completions(command_table, query, verbose)
  File "/Users/chris/.vscode-insiders/extensions/ms-vscode.azurecli-0.1.0/service/azservice/__main__.py", line 182, in get_argument_value_completions

t.logExtensionHostMessage @ extensionHost.ts:337
extensionHost.ts:337 [Extension Host]     list = get_argument_value_list(command_table, query, verbose) + \
  File "/Users/chris/.vscode-insiders/extensions/ms-vscode.azurecli-0.1.0/service/azservice/__main__.py", line 200, in get_argument_value_list
    values = run_argument_value_completer(command, argument, query['arguments'])
  File "/Users/chris/.vscode-insiders/extensions/ms-vscode.azurecli-0.1.0/service/azservice/tooling.py", line 130, in run_argument_value_completer
    return argument.completer('', '', args)
  File "/Users/chris/lib/azure-cli/lib/python2.7/site-packages/azure/cli/core/commands/parameters.py", line 83, in completer

t.logExtensionHostMessage @ extensionHost.ts:337
extensionHost.ts:337 [Extension Host]     return [r.name for r in get_resources_in_resource_group(rg, resource_type=resource_type)]
  File "/Users/chris/lib/azure-cli/lib/python2.7/site-packages/azure/cli/core/commands/parameters.py", line 69, in get_resources_in_resource_group
    return list(rcf.resource_groups.list_resources(resource_group_name, filter=filter_str))
AttributeError: 'ResourceGroupsOperations' object has no attribute 'list_resources'

t.logExtensionHostMessage @ extensionHost.ts:337
extensionHost.ts:337 [Extension Host] Exit code 1, signal null
t.logExtensionHostMessage @ extensionHost.ts:337
extensionHost.ts:337 [Extension Host] Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main

t.logExtensionHostMessage @ extensionHost.ts:337
extensionHost.ts:337 [Extension Host]     "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/chris/.vscode-insiders/extensions/ms-vscode.azurecli-0.1.0/service/azservice/__main__.py", line 335, in <module>
    main()
  File "/Users/chris/.vscode-insiders/extensions/ms-vscode.azurecli-0.1.0/service/azservice/__main__.py", line 326, in main
    response_data = get_completions(group_index, command_table, snippets, request['data'], True)
  File "/Users/chris/.vscode-insiders/extensions/ms-vscode.azurecli-0.1.0/service/azservice/__main__.py", line 114, in get_completions
    return get_argument_value_completions(command_table, query, verbose)
  File "/Users/chris/.vscode-insiders/extensions/ms-vscode.azurecli-0.1.0/service/azservice/__main__.py", line 182, in get_argument_value_completions
    list = get_argument_value_list(command_table, query, verbose) + \
  File "/Users/chris/.vscode-insiders/extensions/ms-vscode.azurecli-0.1.0/service/azservice/__main__.py", line 200, in get_argument_value_list
    values = run_argument_value_completer(command, argument, query['arguments'])
  File "/Users/chris/.vscode-insiders/extensions/ms-vscode.azurecli-0.1.0/service/azservice/tooling.py", line 130, in run_argument_value_completer
    return argument.completer('', '', args)
  File "/Users/chris/lib/azure-cli/lib/python2.7/site-packages/azure/cli/core/commands/parameters.py", line 83, in completer
    return [r.name for r in get_resources_in_resource_group(rg, resource_type=resource_type)]
  File "/Users/chris/lib/azure-cli/lib/python2.7/site-packages/azure/cli/core/commands/parameters.py", line 69, in get_resources_in_resource_group
    return list(rcf.resource_groups.list_resources(resource_group_name, filter=filter_str))
AttributeError: 'ResourceGroupsOperations' object has no attribute 'list_resources'

t.logExtensionHostMessage @ extensionHost.ts:337
extensionHost.ts:337 [Extension Host] Exit code 1, signal null
t.logExtensionHostMessage @ extensionHost.ts:337
extensionHost.ts:337 [Extension Host] Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main

t.logExtensionHostMessage @ extensionHost.ts:337
extensionHost.ts:337 [Extension Host]     "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/chris/.vscode-insiders/extensions/ms-vscode.azurecli-0.1.0/service/azservice/__main__.py", line 335, in <module>
    main()
  File "/Users/chris/.vscode-insiders/extensions/ms-vscode.azurecli-0.1.0/service/azservice/__main__.py", line 326, in main
    response_data = get_completions(group_index, command_table, snippets, request['data'], True)
  File "/Users/chris/.vscode-insiders/extensions/ms-vscode.azurecli-0.1.0/service/azservice/__main__.py", line 114, in get_completions
    return get_argument_value_completions(command_table, query, verbose)
  File "/Users/chris/.vscode-insiders/extensions/ms-vscode.azurecli-0.1.0/service/azservice/__main__.py", line 182, in get_argument_value_completions
    list = get_argument_value_list(command_table, query, verbose) + \
  File "/Users/chris/.vscode-insiders/extensions/ms-vscode.azurecli-0.1.0/service/azservice/__main__.py", line 200, in get_argument_value_list
    values = run_argument_value_completer(command, argument, query['arguments'])
  File "/Users/chris/.vscode-insiders/extensions/ms-vscode.azurecli-0.1.0/service/azservice/tooling.py", line 130, in run_argument_value_completer
    return argument.completer('', '', args)
  File "/Users/chris/lib/azure-cli/lib/python2.7/site-packages/azure/cli/core/commands/parameters.py", line 83, in completer
    return [r.name for r in get_resources_in_resource_group(rg, resource_type=resource_type)]
  File "/Users/chris/lib/azure-cli/lib/python2.7/site-packages/azure/cli/core/commands/parameters.py", line 69, in get_resources_in_resource_group
    return list(rcf.resource_groups.list_resources(resource_group_name, filter=filter_str))
AttributeError: 'ResourceGroupsOperations' object has no attribute 'list_resources'

t.logExtensionHostMessage @ extensionHost.ts:337
extensionHost.ts:337 [Extension Host] Exit code 1, signal null
t.logExtensionHostMessage @ extensionHost.ts:337
extensionHost.ts:337 [Extension Host] Completions not found (webapp deployment user set --user-name)

t.logExtensionHostMessage @ extensionHost.ts:337
extensionHost.ts:337 [Extension Host] Completions not found (webapp deployment user set --password)

t.logExtensionHostMessage @ extensionHost.ts:337
extensionHost.ts:337 [Extension Host] Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main

t.logExtensionHostMessage @ extensionHost.ts:337
extensionHost.ts:337 [Extension Host]     "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/chris/.vscode-insiders/extensions/ms-vscode.azurecli-0.1.0/service/azservice/__main__.py", line 335, in <module>
    main()
  File "/Users/chris/.vscode-insiders/extensions/ms-vscode.azurecli-0.1.0/service/azservice/__main__.py", line 326, in main
    response_data = get_completions(group_index, command_table, snippets, request['data'], True)
  File "/Users/chris/.vscode-insiders/extensions/ms-vscode.azurecli-0.1.0/service/azservice/__main__.py", line 114, in get_completions
    return get_argument_value_completions(command_table, query, verbose)
  File "/Users/chris/.vscode-insiders/extensions/ms-vscode.azurecli-0.1.0/service/azservice/__main__.py", line 182, in get_argument_value_completions
    list = get_argument_value_list(command_table, query, verbose) + \
  File "/Users/chris/.vscode-insiders/extensions/ms-vscode.azurecli-0.1.0/service/azservice/__main__.py", line 200, in get_argument_value_list
    values = run_argument_value_completer(command, argument, query['arguments'])
  File "/Users/chris/.vscode-insiders/extensions/ms-vscode.azurecli-0.1.0/service/azservice/tooling.py", line 130, in run_argument_value_completer
    return argument.completer('', '', args)
  File "/Users/chris/lib/azure-cli/lib/python2.7/site-packages/azure/cli/core/commands/parameters.py", line 83, in completer
    return [r.name for r in get_resources_in_resource_group(rg, resource_type=resource_type)]
  File "/Users/chris/lib/azure-cli/lib/python2.7/site-packages/azure/cli/core/commands/parameters.py", line 69, in get_resources_in_resource_group
    return list(rcf.resource_groups.list_resources(resource_group_name, filter=filter_str))
AttributeError: 'ResourceGroupsOperations' object has no attribute 'list_resources'

t.logExtensionHostMessage @ extensionHost.ts:337
extensionHost.ts:337 [Extension Host] Exit code 1, signal null
t.logExtensionHostMessage @ extensionHost.ts:337
extensionHost.ts:337 [Extension Host] Argument not found (webapp deployment source config-local-git --)

t.logExtensionHostMessage @ extensionHost.ts:337
4extensionHost.ts:337 [Extension Host] Completions not found (webapp config set --node-version)

t.logExtensionHostMessage @ extensionHost.ts:337
extensionHost.ts:337 [Extension Host] Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main

t.logExtensionHostMessage @ extensionHost.ts:337
extensionHost.ts:337 [Extension Host]     "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/chris/.vscode-insiders/extensions/ms-vscode.azurecli-0.1.0/service/azservice/__main__.py", line 335, in <module>
    main()
  File "/Users/chris/.vscode-insiders/extensions/ms-vscode.azurecli-0.1.0/service/azservice/__main__.py", line 326, in main
    response_data = get_completions(group_index, command_table, snippets, request['data'], True)
  File "/Users/chris/.vscode-insiders/extensions/ms-vscode.azurecli-0.1.0/service/azservice/__main__.py", line 114, in get_completions
    return get_argument_value_completions(command_table, query, verbose)
  File "/Users/chris/.vscode-insiders/extensions/ms-vscode.azurecli-0.1.0/service/azservice/__main__.py", line 182, in get_argument_value_completions
    list = get_argument_value_list(command_table, query, verbose) + \
  File "/Users/chris/.vscode-insiders/extensions/ms-vscode.azurecli-0.1.0/service/azservice/__main__.py", line 200, in get_argument_value_list

t.logExtensionHostMessage @ extensionHost.ts:337
extensionHost.ts:337 [Extension Host]     values = run_argument_value_completer(command, argument, query['arguments'])
  File "/Users/chris/.vscode-insiders/extensions/ms-vscode.azurecli-0.1.0/service/azservice/tooling.py", line 130, in run_argument_value_completer
    return argument.completer('', '', args)
  File "/Users/chris/lib/azure-cli/lib/python2.7/site-packages/azure/cli/core/commands/parameters.py", line 83, in completer
    return [r.name for r in get_resources_in_resource_group(rg, resource_type=resource_type)]

t.logExtensionHostMessage @ extensionHost.ts:337
extensionHost.ts:337 [Extension Host]   File "/Users/chris/lib/azure-cli/lib/python2.7/site-packages/azure/cli/core/commands/parameters.py", line 69, in get_resources_in_resource_group
    return list(rcf.resource_groups.list_resources(resource_group_name, filter=filter_str))
AttributeError: 'ResourceGroupsOperations' object has no attribute 'list_resources'

t.logExtensionHostMessage @ extensionHost.ts:337
extensionHost.ts:337 [Extension Host] Exit code 1, signal null
t.logExtensionHostMessage @ extensionHost.ts:337
extensionHost.ts:337 [Extension Host] Completions not found (webapp config set --node-version)

t.logExtensionHostMessage @ extensionHost.ts:337
messageService.ts:125 Extension host terminated unexpectedly. Please reload the window to recover.
e.doShow @ messageService.ts:125
extensionHost.ts:388 Extension host terminated unexpectedly. Code:  87  Signal:  null
t.onExit @ extensionHost.ts:388
extensionHost.ts:180 Extension Host
extensionHost.ts:181 The module native-watchdog has detected that the event loop is unresponsive.
Here is the JavaScript stack trace:
======================================native-watchdog======================================
tryOnTimeout (timers.js:1:1)
Timer.listOnTimeout (timers.js:214:5)
======================================native-watchdog======================================
The module native-watchdog will now terminate the process with exit code 87.
```

Azure CLI version:

``` console
~/src/myExpressApp$ az --version
azure-cli (2.0.6)

acr (2.0.4)
acs (2.0.6)
appservice (0.1.6)
batch (2.0.4)
cdn (0.0.2)
cloud (2.0.2)
cognitiveservices (0.1.2)
command-modules-nspkg (2.0.0)
component (2.0.4)
configure (2.0.6)
container (0.1.4)
core (2.0.6)
cosmosdb (0.1.6)
dla (0.0.6)
dls (0.0.6)
documentdb (0.1.5)
feedback (2.0.2)
find (0.2.2)
interactive (0.3.2)
iot (0.1.5)
keyvault (2.0.4)
lab (0.0.4)
monitor (0.0.4)
network (2.0.6)
nspkg (3.0.0)
profile (2.0.4)
rdbms (0.0.1)
redis (0.2.3)
resource (2.0.6)
role (2.0.4)
sf (1.0.1)
shell (0.2.2)
sql (2.0.3)
storage (2.0.6)
vm (2.0.6)

Python (Darwin) 2.7.10 (default, Oct 23 2015, 19:19:21)
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)]

Python location '/Users/chris/lib/azure-cli/bin/python'
```

I had been using the Azure CLI extension and was not getting completions against the webapp --name parameter. Will log that as a separate issue.

**Comment by chrisdias** [comment]
completions issue: https://github.com/Microsoft/vscode-azurecli/issues/15
