### ISSUE TITLE
No completions for webapp --name

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode-azurecli#15]
``` bash
az login
az webapp browse --name 
```

result: no completions

``` bash
az webapp browse --resource-group 
```

result: completions (goodness!)

``` bash
az webapp browse --resource-group fix-walkthrough-rg --name 
``` 

result: still no completions

Here' what I see in the dev tools console:

``` console
Extension Host] Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main

t.logExtensionHostMessage @ /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:29
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:29 [Extension Host]     "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/chris/.vscode-insiders/extensions/ms-vscode.azurecli-0.1.0/service/azservice/__main__.py", line 335, in <module>
    main()
  File "/Users/chris/.vscode-insiders/extensions/ms-vscode.azurecli-0.1.0/service/azservice/__main__.py", line 326, in main
    response_data = get_completions(group_index, command_table, snippets, request['data'], True)
  File "/Users/chris/.vscode-insiders/extensions/ms-vscode.azurecli-0.1.0/service/azservice/__main__.py", line 114, in get_completions
    return get_argument_value_completions(command_table, query, verbose)
  File "/Users/chris/.vscode-insiders/extensions/ms-vscode.azurecli-0.1.0/service/azservice/__main__.py", line 182, in get_argument_value_completions
    list = get_argument_value_list(command_table, query, verbose) + \
  File "/Users/chris/.vscode-insiders/extensions/ms-vscode.azurecli-0.1.0/service/azservice/__main__.py", line 200, in get_argument_value_list

t.logExtensionHostMessage @ /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:29
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:29 [Extension Host]     values = run_argument_value_completer(command, argument, query['arguments'])
  File "/Users/chris/.vscode-insiders/extensions/ms-vscode.azurecli-0.1.0/service/azservice/tooling.py", line 130, in run_argument_value_completer

t.logExtensionHostMessage @ /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:29
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:29 [Extension Host]     return argument.completer('', '', args)
  File "/Users/chris/lib/azure-cli/lib/python2.7/site-packages/azure/cli/core/commands/parameters.py", line 83, in completer

t.logExtensionHostMessage @ /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:29
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:29 [Extension Host]     return [r.name for r in get_resources_in_resource_group(rg, resource_type=resource_type)]
  File "/Users/chris/lib/azure-cli/lib/python2.7/site-packages/azure/cli/core/commands/parameters.py", line 69, in get_resources_in_resource_group

t.logExtensionHostMessage @ /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:29
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:29 [Extension Host]     return list(rcf.resource_groups.list_resources(resource_group_name, filter=filter_str))
AttributeError: 'ResourceGroupsOperations' object has no attribute 'list_resources'

t.logExtensionHostMessage @ /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:29
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:29 [Extension Host] Exit code 1, signal null
t.logExtensionHostMessage @ /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:29
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:29 [Extension Host] Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main

t.logExtensionHostMessage @ /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:29
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:29 [Extension Host]     "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/chris/.vscode-insiders/extensions/ms-vscode.azurecli-0.1.0/service/azservice/__main__.py", line 335, in <module>
    main()

t.logExtensionHostMessage @ /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:29
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:29 [Extension Host]   File "/Users/chris/.vscode-insiders/extensions/ms-vscode.azurecli-0.1.0/service/azservice/__main__.py", line 326, in main
    
t.logExtensionHostMessage @ /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:29
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:29 [Extension Host] response_data = get_completions(group_index, command_table, snippets, request['data'], True)
  File "/Users/chris/.vscode-insiders/extensions/ms-vscode.azurecli-0.1.0/service/azservice/__main__.py", line 114, in get_completions
    return get_argument_value_completions(command_table, query, verbose)
  File "/Users/chris/.vscode-insiders/extensions/ms-vscode.azurecli-0.1.0/service/azservice/__main__.py", line 182, in get_argument_value_completions

t.logExtensionHostMessage @ /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:29
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:29 [Extension Host]     list = get_argument_value_list(command_table, query, verbose) + \
  File "/Users/chris/.vscode-insiders/extensions/ms-vscode.azurecli-0.1.0/service/azservice/__main__.py", line 200, in get_argument_value_list

t.logExtensionHostMessage @ /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:29
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:29 [Extension Host]     values = run_argument_value_completer(command, argument, query['arguments'])
  File "/Users/chris/.vscode-insiders/extensions/ms-vscode.azurecli-0.1.0/service/azservice/tooling.py", line 130, in run_argument_value_completer

t.logExtensionHostMessage @ /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:29
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:29 [Extension Host]     return argument.completer('', '', args)
  File "/Users/chris/lib/azure-cli/lib/python2.7/site-packages/azure/cli/core/commands/parameters.py", line 83, in completer
    return [r.name for r in get_resources_in_resource_group(rg, resource_type=resource_type)]
  File "/Users/chris/lib/azure-cli/lib/python2.7/site-packages/azure/cli/core/commands/parameters.py", line 69, in get_resources_in_resource_group

t.logExtensionHostMessage @ /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:29
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:29 [Extension Host]     return list(rcf.resource_groups.list_resources(resource_group_name, filter=filter_str))
AttributeError: 'ResourceGroupsOperations' object has no attribute 'list_resources'

t.logExtensionHostMessage @ /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:29
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:29 [Extension Host] Exit code 1, signal null
```

**Comment by chrisdias** [comment]
dupe of #10
