### ISSUE TITLE
All azure commands in VSC are appearing as not found.

### ISSUE THREAD

**Issue by rfkamal** [Microsoft/vscode-azurecli#40]
Hi,

I have installed the Azure Tools in Visual Studio Code. However, when I attempt to sign in to Azure, or use any of the Azure commands in fact, I am getting the notifications an example of which is: 'command 'azure-account.login' not found' another example is 'command 'azureFunctions.createNewProject' not found'.

I have uninstalled the Azure Tools and re-installed them, downloaded and installed the Azure Functions Core Tools globally and locally, uninstalled and reinstalled VSC into both program files and AppData folders. I have installed the Azure CLI, however nothing works.

I have attached a screenshot of the notifications.

<img width="240" alt="azure commands" src="https://user-images.githubusercontent.com/30114430/47561145-5f852480-d912-11e8-8415-72690eed1aed.PNG">

Thanks for your help.

Regards,

Rami

**Comment by chrmarti** [comment]
Anything in the console (Help > Toggle Developer Tools)? The first errors in the console would be interesting since these might have triggered all others.

**Comment by rfkamal** [comment]
Hi Chrmarti, thanks for the reply.

I get the following error in the console:
Error: command 'azureFunctions.createFunction' not found
    at t._tryExecuteCommand (file:///C:/Users/934873/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3030:36)
    at file:///C:/Users/934873/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3029:885
    at Object.g [as _notify] (file:///C:/Users/934873/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:160:729)
    at Object.enter (file:///C:/Users/934873/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:164:61)
    at n.Class.derive._oncancel._run (file:///C:/Users/934873/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:165:902)
    at n.Class.derive._oncancel._completed (file:///C:/Users/934873/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:165:343)
    at l (file:///C:/Users/934873/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:168:855)
    at n.Class.derive.join.r.forEach.G.then.o.(anonymous function) (file:///C:/Users/934873/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:169:45)
    at Object.g [as _notify] (file:///C:/Users/934873/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:160:729)
    at Object.enter (file:///C:/Users/934873/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:164:61)
    at n.Class.derive._oncancel._run (file:///C:/Users/934873/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:165:902)
    at n.Class.derive._oncancel._completed (file:///C:/Users/934873/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:165:343)
    at l (file:///C:/Users/934873/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:168:855)
    at n.Class.derive.join.r.forEach.G.then.o.(anonymous function) (file:///C:/Users/934873/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:169:45)
    at Object.g [as _notify] (file:///C:/Users/934873/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:160:729)
    at Object.enter (file:///C:/Users/934873/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:164:61)
    at n.Class.derive._creator._run (file:///C:/Users/934873/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:165:902)
    at n.Class.derive._creator._completed (file:///C:/Users/934873/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:165:343)
    at Object.g [as _notify] (file:///C:/Users/934873/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:160:729)
    at Object.enter (file:///C:/Users/934873/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:164:61)
    at n.Class.derive._oncancel._run (file:///C:/Users/934873/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:165:902)
    at n.Class.derive._oncancel._completed (file:///C:/Users/934873/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:165:343)
    at e.resolveOk (file:///C:/Users/934873/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3186:248)
    at t._receiveReply (file:///C:/Users/934873/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3266:305)
    at t._receiveOneMessage (file:///C:/Users/934873/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3264:600)
    at file:///C:/Users/934873/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3262:81
    at e.fire (file:///C:/Users/934873/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:181:218)
    at a (file:///C:/Users/934873/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:318:348)
    at Socket.n._socketDataListener (file:///C:/Users/934873/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:318:567)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)

Saying that, after opening and clearing the console. The Azure commands appear to have started working.

**Comment by chrmarti** [comment]
Could be https://github.com/Microsoft/vscode/issues/58918. Could you try the insiders build and see if it is fixed there? https://code.visualstudio.com/insiders/

**Comment by rfkamal** [comment]
Yes, it is working in the insider build it is working with no issues.
Thank you for your help.

**Comment by chrmarti** [comment]
Great, the insiders version will soon make it into a new stable release. Closing.

**Comment by siddheshsagar** [comment]
I do had faced the same issue, I don't know how this happened but when I didn't got any solution on this issue, I tried to create new project folder for the same project. In the new project I didn't even able to create the functions.
All I did is I deleted the project folder from where this issue started. It resolved my issue.
