### ISSUE TITLE
ImportError: cannot import name 'DEFAULTS_SECTION'

### ISSUE THREAD

**Issue by hursitcakmakci** [Microsoft/vscode-azurecli#50]
I installed an extension Azure CLI Tools and feature Intellisense doesn't autocomplete. I get the following error in developer tools.

**My Version of Software are:**

Azure-CLI version: 2.0.62
Azure Tools Version: 0.0.6
Azure CLI Tools Version: 0.4.4
VS Code Version: 1.33.1

**Developer Tools**

Traceback (most recent call last):
  File "C:\Users\hursi\.vscode\extensions\ms-vscode.azurecli-0.4.4\service\start.py", line 6, in <module>
    import azservice.__main__
  File "C:\Users\hursi\.vscode\extensions\ms-vscode.azurecli-0.4.4\service\azservice\__main__.py", line 17, in <module>
    from azservice.tooling import GLOBAL_ARGUMENTS, initialize, load_command_table, get_help, get_current_subscription, get_configured_defaults, get_defaults, is_required, run_argument_value_completer, get_arguments, load_arguments, arguments_loaded
  File "C:\Users\hursi\.vscode\extensions\ms-vscode.azurecli-0.4.4\service\azservice\tooling.py", line 12, in <module>
    from azservice.tooling2 import GLOBAL_ARGUMENTS, initialize, load_command_table, get_help, get_current_subscription, get_configured_defaults, get_defaults, is_required, run_argument_value_completer, get_arguments, load_arguments, arguments_loaded
  File "C:\Users\hursi\.vscode\extensions\ms-vscode.azurecli-0.4.4\service\azservice\tooling2.py", line 17, in <module>
    from azure.cli.core._config import GLOBAL_CONFIG_PATH, DEFAULTS_SECTION
**ImportError: cannot import name 'DEFAULTS_SECTION'**

t.log @ console.ts:134

**Comment by Variour** [comment]
Same issue as #19?

**Comment by Shaun-Cox** [comment]
The related change in azure-cli that likely caused this (in case it wasn't obvious): https://github.com/Azure/azure-cli/pull/8940/files/64b13c0f288d8ade6bfc061d0f4fbd6cbf6a7d1c
