### ISSUE TITLE
IntelliSense doesn't work after a few lines of code

### ISSUE THREAD

**Issue by wshamroukh** [microsoft/vscode-azurecli#64]
Hi Team,

I have noticed this since i started working on Azure CLI Tools extension. The intelliSense doesn't kick in at all and if i press ctrl+space to force it to show suggestions, the loading message stays there forever. The only way to get it to run back, is by closing vscode and reopen it

here is what i see from the console
`  ERR canceled
console.ts:137 [Extension Host] Completions not found (network route-table route create --address-prefix)
t.log @ console.ts:137
console.ts:137 [Extension Host] Completions not found (network route-table route create --name)
t.log @ console.ts:137
3log.ts:196   ERR canceled
console.ts:137 [Extension Host] Completions not found (network route-table route create --next-hop-ip-address)
t.log @ console.ts:137
6log.ts:196   ERR canceled
console.ts:137 [Extension Host] Completions not found (network vnet subnet update --name)
t.log @ console.ts:137
2log.ts:196   ERR canceled
console.ts:137 [Extension Host] Completions not found (network vnet subnet update --name)
t.log @ console.ts:137
6log.ts:196   ERR canceled
console.ts:137 [Extension Host] Traceback (most recent call last):
  File "c:\Users\waddahs\.vscode\extensions\ms-vscode.azurecli-0.4.6\service\start.py", line 6, in <module>
    import azservice.__main__
  File "c:\Users\waddahs\.vscode\extensions\ms-vscode.azurecli-0.4.6\service\azservice\__main__.py", line 370, in <module>
    main()
  File "c:\Users\waddahs\.vscode\extensions\ms-vscode.azurecli-0.4.6\service\azservice\__main__.py", line 356, in main
    response_data = get_hover_text(group_index, command_table, request['data']['command'])
  File "c:\Users\waddahs\.vscode\extensions\ms-vscode.azurecli-0.4.6\service\azservice\__main__.py", line 262, in get_hover_text
    return { 'paragraphs': [ '`' + ' '.join(get_options(argument.options_list)) + '`' + ('*' if req else '') + ': ' + argument.type.settings.get('help')
TypeError: can only concatenate str (not "NoneType") to str
t.log @ console.ts:137
console.ts:137 [Extension Host] Exit code 0, signal null
t.log @ console.ts:137
console.ts:137 [Extension Host] Python process terminated with exit code 0, signal null.
t.log @ console.ts:137
log.ts:196   ERR Python process terminated with exit code 0, signal null.
console.ts:137 [Extension Host] Traceback (most recent call last):
  File "c:\Users\waddahs\.vscode\extensions\ms-vscode.azurecli-0.4.6\service\start.py", line 6, in <module>
    import azservice.__main__
  File "c:\Users\waddahs\.vscode\extensions\ms-vscode.azurecli-0.4.6\service\azservice\__main__.py", line 370, in <module>
    main()
  File "c:\Users\waddahs\.vscode\extensions\ms-vscode.azurecli-0.4.6\service\azservice\__main__.py", line 356, in main
    response_data = get_hover_text(group_index, command_table, request['data']['command'])
  File "c:\Users\waddahs\.vscode\extensions\ms-vscode.azurecli-0.4.6\service\azservice\__main__.py", line 262, in get_hover_text
    return { 'paragraphs': [ '`' + ' '.join(get_options(argument.options_list)) + '`' + ('*' if req else '') + ': ' + argument.type.settings.get('help')
TypeError: can only concatenate str (not "NoneType") to str
t.log @ console.ts:137
console.ts:137 [Extension Host] Exit code 0, signal null
t.log @ console.ts:137
log.ts:196   ERR Python process terminated with exit code 0, signal null.
3log.ts:196   ERR canceled
console.ts:137 [Extension Host] Completions not found (network vnet subnet update --route-table)
t.log @ console.ts:137
31log.ts:196   ERR canceled
3log.ts:196   ERR canceled`

Any help is really appreciated

**Comment by chrmarti** [comment]
Which version of the CLI are you using?

**Comment by wshamroukh** [comment]
@chrmarti i am using the latest i guess - 1.41.1

Version: 1.41.1 (user setup)
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T14:58:56.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18363

**Comment by wshamroukh** [comment]
` az --version
azure-cli                         2.0.80

command-modules-nspkg              2.0.3
core                              2.0.80
nspkg                              3.0.4
telemetry                          1.0.4

Extensions:
azure-firewall                     0.1.5
front-door                         1.0.2
virtual-wan                        0.1.2

Python location 'C:\Python\python.exe'
Extensions directory 'C:\Users\waddahs\.azure\cliextensions'

Python (Windows) 3.8.1 (tags/v3.8.1:1b293b6, Dec 18 2019, 23:11:46) [MSC v.1916 64 bit (AMD64)]

Legal docs and information: aka.ms/AzureCliLegal



Your CLI is up-to-date.

Please let us know how we are doing: https://aka.ms/clihats`

**Comment by wshamroukh** [comment]
It is there:
```
dir C:\Users\myuser\.vscode\extensions\ms-vscode.azurecli-0.5.0\service\azservice

    Directory: C:\Users\myuser\.vscode\extensions\ms-vscode.azurecli-0.5.0\service\azservice

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----          12/10/2021 10:43 AM                __pycache__
-a---          11/10/2021 11:28 PM            367 __init__.py
-a---          11/10/2021 11:28 PM            194 __init__.pyc
-a---          11/10/2021 11:28 PM          18295 __main__.py
-a---          11/10/2021 11:28 PM           1017 tooling.py
-a---          11/10/2021 11:28 PM            856 tooling.pyc
-a---          11/10/2021 11:28 PM           6144 tooling1.py
-a---          11/10/2021 11:28 PM           7048 tooling2.py
```
